use serde::Deserialize;
use std::env;
use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const BUILD_METADATA_SCHEMA_VERSION: u8 = 1;
const MAX_SAFE_INTEGER: u64 = 9_007_199_254_740_991;
const GENERATED_METADATA_FILE: &str = "wardrobe_build_metadata_v1.rs";

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BuildMetadataV1 {
    schema_version: u8,
    application_id: String,
    application_version: String,
    release_sequence: u64,
}

#[derive(Debug, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
}

#[derive(Debug, Deserialize)]
struct CargoPackage {
    version: String,
}

#[derive(Debug, Deserialize)]
struct TauriConfiguration {
    identifier: String,
    version: String,
}

#[derive(Debug, Deserialize)]
struct NpmPackage {
    version: String,
}

fn main() {
    let manifest_dir = PathBuf::from(
        env::var_os("CARGO_MANIFEST_DIR").expect("Cargo did not provide CARGO_MANIFEST_DIR"),
    );
    let repository_root = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("wardrobe-platform must be inside the repository crates directory");
    let metadata_inputs = metadata_input_paths(repository_root);
    for path in &metadata_inputs {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    let generated = generated_metadata_constants(repository_root)
        .unwrap_or_else(|error| panic!("Wardrobe build metadata validation failed: {error}"));
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo did not provide OUT_DIR"));
    fs::write(out_dir.join(GENERATED_METADATA_FILE), generated)
        .expect("failed to write generated Wardrobe build metadata constants");

    build_photokit(&manifest_dir);
}

pub(crate) fn generated_metadata_constants(repository_root: &Path) -> Result<String, String> {
    let paths = metadata_input_paths(repository_root);
    let metadata: BuildMetadataV1 = read_json(&paths[0])?;
    if metadata.schema_version != BUILD_METADATA_SCHEMA_VERSION {
        return Err(format!(
            "{}: schema_version must be {}, found {}",
            paths[0].display(),
            BUILD_METADATA_SCHEMA_VERSION,
            metadata.schema_version
        ));
    }
    validate_application_id(&metadata.application_id, &paths[0])?;
    validate_version(&metadata.application_version, &paths[0])?;
    if metadata.release_sequence == 0 || metadata.release_sequence > MAX_SAFE_INTEGER {
        return Err(format!(
            "{}: release_sequence must be between 1 and {MAX_SAFE_INTEGER}, found {}",
            paths[0].display(),
            metadata.release_sequence
        ));
    }

    let desktop_cargo: CargoManifest = read_toml(&paths[1])?;
    let tauri: TauriConfiguration = read_json(&paths[2])?;
    let root_package: NpmPackage = read_json(&paths[3])?;
    let desktop_package: NpmPackage = read_json(&paths[4])?;

    require_equal(
        "application identifier",
        &metadata.application_id,
        &paths[0],
        &tauri.identifier,
        &paths[2],
    )?;
    for (version, path) in [
        (&desktop_cargo.package.version, &paths[1]),
        (&tauri.version, &paths[2]),
        (&root_package.version, &paths[3]),
        (&desktop_package.version, &paths[4]),
    ] {
        validate_version(version, path)?;
        require_equal(
            "application version",
            &metadata.application_version,
            &paths[0],
            version,
            path,
        )?;
    }

    Ok(format!(
        "// @generated by crates/wardrobe-platform/build.rs; do not edit.\n\
         pub const INSTALLED_UPDATE_APPLICATION_ID_V1: &str = {:?};\n\
         pub const INSTALLED_UPDATE_APPLICATION_VERSION_V1: &str = {:?};\n\
         pub const INSTALLED_UPDATE_RELEASE_SEQUENCE_V1: u64 = {};\n",
        metadata.application_id, metadata.application_version, metadata.release_sequence
    ))
}

fn metadata_input_paths(repository_root: &Path) -> [PathBuf; 5] {
    [
        repository_root.join("release/wardrobe-build-metadata-v1.json"),
        repository_root.join("src-tauri/Cargo.toml"),
        repository_root.join("src-tauri/tauri.conf.json"),
        repository_root.join("package.json"),
        repository_root.join("apps/desktop-ui/package.json"),
    ]
}

fn read_json<T>(path: &Path) -> Result<T, String>
where
    T: for<'de> Deserialize<'de>,
{
    let contents =
        fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    serde_json::from_str(&contents)
        .map_err(|error| format!("{}: invalid JSON: {error}", path.display()))
}

fn read_toml<T>(path: &Path) -> Result<T, String>
where
    T: for<'de> Deserialize<'de>,
{
    let contents =
        fs::read_to_string(path).map_err(|error| format!("{}: {error}", path.display()))?;
    toml::from_str(&contents).map_err(|error| format!("{}: invalid TOML: {error}", path.display()))
}

fn validate_application_id(value: &str, path: &Path) -> Result<(), String> {
    if value.is_empty()
        || value.len() > 128
        || value.starts_with('.')
        || value.ends_with('.')
        || value.split('.').count() < 2
        || value
            .bytes()
            .any(|byte| !(byte.is_ascii_alphanumeric() || byte == b'-' || byte == b'.'))
    {
        return Err(format!(
            "{}: application_id is not a valid reverse-domain identifier: {value:?}",
            path.display()
        ));
    }
    Ok(())
}

fn validate_version(value: &str, path: &Path) -> Result<(), String> {
    let components: Vec<&str> = value.split('.').collect();
    if components.len() != 3
        || value.len() > 64
        || components.iter().any(|component| {
            component.is_empty()
                || (component.len() > 1 && component.starts_with('0'))
                || component.parse::<u32>().is_err()
        })
    {
        return Err(format!(
            "{}: application version must contain exactly three canonical u32 components: {value:?}",
            path.display()
        ));
    }
    Ok(())
}

fn require_equal(
    field: &str,
    authoritative: &str,
    authoritative_path: &Path,
    candidate: &str,
    candidate_path: &Path,
) -> Result<(), String> {
    if authoritative != candidate {
        return Err(format!(
            "{field} mismatch: {} declares {authoritative:?}, but {} declares {candidate:?}",
            authoritative_path.display(),
            candidate_path.display()
        ));
    }
    Ok(())
}

fn build_photokit(manifest_dir: &Path) {
    println!("cargo:rerun-if-env-changed=CARGO_FEATURE_PHOTOKIT_NATIVE");
    if env::var_os("CARGO_FEATURE_PHOTOKIT_NATIVE").is_none() {
        return;
    }

    let target = env::var("TARGET").expect("Cargo did not provide TARGET");
    if !target.ends_with("-apple-darwin") {
        return;
    }

    let package_dir = manifest_dir
        .parent()
        .and_then(Path::parent)
        .expect("wardrobe-platform must be inside the repository crates directory")
        .join("native/photokit");
    emit_rerun_rules(&package_dir);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo did not provide OUT_DIR"));
    let scratch_dir = out_dir.join("photokit-swift");
    let configuration = match env::var("PROFILE").as_deref() {
        Ok("release") => "release",
        _ => "debug",
    };
    let architecture = match target.split('-').next() {
        Some("aarch64") => "arm64",
        Some("x86_64") => "x86_64",
        other => panic!("unsupported macOS architecture for PhotoKit: {other:?}"),
    };

    let status = Command::new("swift")
        .args(["build", "--package-path"])
        .arg(&package_dir)
        .args(["--scratch-path"])
        .arg(&scratch_dir)
        .args([
            "--configuration",
            configuration,
            "--arch",
            architecture,
            "--product",
            "WardrobePhotoKit",
        ])
        .status()
        .expect("failed to launch SwiftPM for WardrobePhotoKit");
    assert!(status.success(), "failed to build WardrobePhotoKit");

    let archive = find_file(&scratch_dir, OsStr::new("libWardrobePhotoKit.a"))
        .expect("SwiftPM did not produce libWardrobePhotoKit.a");
    println!(
        "cargo:rustc-link-search=native={}",
        archive
            .parent()
            .expect("Swift archive must have a parent")
            .display()
    );
    println!("cargo:rustc-link-lib=static=WardrobePhotoKit");

    for framework in [
        "AppKit",
        "Foundation",
        "ImageIO",
        "Photos",
        "PhotosUI",
        "UniformTypeIdentifiers",
    ] {
        println!("cargo:rustc-link-lib=framework={framework}");
    }

    if let Some(swiftc) = command_output("xcrun", &["--find", "swiftc"]) {
        if let Some(toolchain) = Path::new(swiftc.trim()).parent().and_then(Path::parent) {
            println!(
                "cargo:rustc-link-search=native={}",
                toolchain.join("lib/swift/macosx").display()
            );
        }
    }
    if let Some(sdk) = command_output("xcrun", &["--sdk", "macosx", "--show-sdk-path"]) {
        println!(
            "cargo:rustc-link-search=native={}",
            Path::new(sdk.trim()).join("usr/lib/swift").display()
        );
    }
    println!("cargo:rustc-link-arg=-Wl,-rpath,/usr/lib/swift");
}

fn emit_rerun_rules(root: &Path) {
    println!(
        "cargo:rerun-if-changed={}",
        root.join("Package.swift").display()
    );
    let mut pending = vec![root.join("Sources")];
    while let Some(path) = pending.pop() {
        let entries = fs::read_dir(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
        for entry in entries {
            let path = entry.expect("failed to inspect PhotoKit source").path();
            if path.is_dir() {
                pending.push(path);
            } else {
                println!("cargo:rerun-if-changed={}", path.display());
            }
        }
    }
}

fn find_file(root: &Path, name: &OsStr) -> Option<PathBuf> {
    let entries = fs::read_dir(root).ok()?;
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if let Some(found) = find_file(&path, name) {
                return Some(found);
            }
        } else if path.file_name() == Some(name) {
            return Some(path);
        }
    }
    None
}

fn command_output(program: &str, arguments: &[&str]) -> Option<String> {
    let output = Command::new(program).args(arguments).output().ok()?;
    if !output.status.success() {
        return None;
    }
    String::from_utf8(output.stdout).ok()
}
