from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path
import tempfile
import unittest
from unittest import mock

from tools.evaluators import p02_manual_catalog
from tools.evaluators import run as evaluator_run


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def command_result(returncode: int = 0) -> p02_manual_catalog.CommandResult:
    return p02_manual_catalog.CommandResult(
        returncode=returncode,
        output_sha256=hashlib.sha256(b"synthetic output").hexdigest(),
        output_bytes=64,
        duration_ms=10,
    )


def read_json(path: Path) -> dict[str, object]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_valid_fixture(root: Path) -> None:
    migration_1 = "CREATE TABLE foundation(id INTEGER PRIMARY KEY) STRICT;\n"
    migration_2 = "CREATE TABLE catalog(id INTEGER PRIMARY KEY) STRICT;\n"
    commands = p02_manual_catalog.P02_COMMANDS
    command_lines = "\n".join(f"fn {command}() {{}}" for command in commands)
    tauri_lines = "\n".join(
        f"#[tauri::command]\nfn {command}() {{}}" for command in commands
    )
    permissions = [
        "allow-" + command.replace("_", "-") for command in commands
    ]
    files = {
        "Cargo.lock": """
version = 4

[[package]]
name = "image"
version = "0.25.10"

[[package]]
name = "mail-parser"
version = "0.11.5"
""",
        "crates/wardrobe-core/src/bindings.rs": """
fn generated_bindings_are_current() { typescript_bindings(); }
""",
        "crates/wardrobe-core/src/contracts.rs": """
#[serde(deny_unknown_fields)]
struct Request { schema_version: u8 }
""",
        "crates/wardrobe-core/src/service.rs": command_lines,
        "crates/wardrobe-core/src/bin/generate-bindings.rs": """
fn main() { wardrobe_core::typescript_bindings(); }
""",
        "apps/desktop-ui/src/generated/contracts.ts": (
            "// @generated by wardrobe-core. Do not edit.\n"
        ),
        "crates/wardrobe-platform/Cargo.toml": """
[dependencies]
image = { version = "=0.25.10" }
mail-parser = "=0.11.5"
""",
        "crates/wardrobe-platform/src/database.rs": """
const ONE: &str = include_str!("../migrations/0001_foundation.sql");
const TWO: &str = include_str!("../migrations/0002_manual_catalog.sql");
const MIGRATIONS: &[Migration] = &[
    Migration { version: 1 },
    Migration { version: 2 },
];
fn validate_migration_source() {}
fn verify_applied_migrations() {}
struct Sidecar { source_database_sha256: String, backup_sha256: String }
""",
        "crates/wardrobe-platform/src/imports.rs": """
fn import() {
    O_NOFOLLOW; source_provenance; quarantine; ImageReader; Limits;
    MessageParser; Sha256::digest(raw); occurrences.entry(hash.clone());
    mime; mbox;
}
""",
        "crates/wardrobe-platform/src/catalog_repository.rs": """
fn catalog() {
    TransactionBehavior::Immediate;
    catalog_revision; expected_catalog_revision;
    append_compensating_undo; preview_deletion; list_deletion_plan_items;
}
fn production_import_catalog_restart_undo_and_deletion_smoke() {}
""",
        "crates/wardrobe-platform/migrations/0001_foundation.sql": migration_1,
        "crates/wardrobe-platform/migrations/0001_foundation.sha256": (
            hashlib.sha256(migration_1.encode()).hexdigest() + "\n"
        ),
        "crates/wardrobe-platform/migrations/0002_manual_catalog.sql": migration_2,
        "crates/wardrobe-platform/migrations/0002_manual_catalog.sha256": (
            hashlib.sha256(migration_2.encode()).hexdigest() + "\n"
        ),
        "src-tauri/src/lib.rs": (
            tauri_lines
            + "\nfn register() { "
            + "; ".join(f"{command}()" for command in commands)
            + "; }\n"
        ),
        "src-tauri/build.rs": (
            "fn main() { let commands = ["
            + ",".join(f'"{command}"' for command in commands)
            + "]; }\n"
        ),
        "src-tauri/capabilities/main.json": json.dumps(
            {"permissions": permissions}
        ),
        "apps/desktop-ui/package.json": json.dumps(
            {
                "scripts": {
                    "build": "vite build",
                    "test": "vitest run",
                    "test:e2e": "playwright test",
                    "check:production-transport": "node check.mjs",
                }
            }
        ),
        "apps/desktop-ui/vite.config.ts": """
const e2e = mode === "e2e";
if (e2e && process.env.WARDROBE_E2E !== "1") throw Error();
""",
        "apps/desktop-ui/scripts/check-production-transport.mjs": """
const marker = "__WARDROBE_E2E_TRANSPORT__";
const flag = "WARDROBE_E2E";
""",
        "apps/desktop-ui/src/invoke-transport.ts": (
            'import { invoke } from "@tauri-apps/api/core";\n'
        ),
        "apps/desktop-ui/src/e2e/invoke-transport.ts": (
            'const marker = "__WARDROBE_E2E_TRANSPORT__";\n'
        ),
        "apps/desktop-ui/src/catalog-bridge.ts": command_lines,
        "apps/desktop-ui/e2e/manual-catalog.spec.ts": """
AxeBuilder; serious; critical; p02-desktop.png; p02-mobile.png;
setViewportSize; expected_catalog_revision;
""",
        "apps/desktop-ui/playwright.config.ts": 'devices["Desktop Chrome"]',
    }
    for relative, text in files.items():
        write(root / relative, text)


class SourceValidationTests(unittest.TestCase):
    def test_accepts_complete_production_contract(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_valid_fixture(root)
            result = p02_manual_catalog.validate_source_contract(root)

        self.assertTrue(
            all(not messages for messages in result.errors.values())
        )
        self.assertEqual(
            set(p02_manual_catalog.P02_COMMANDS),
            set(result.registered_commands),
        )
        self.assertTrue(result.production_transport_isolated)
        self.assertEqual(
            64, len(result.migration_sha256["0002_manual_catalog"])
        )

    def test_source_mutations_fail_closed(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_valid_fixture(root)
            write(
                root
                / "crates/wardrobe-platform/migrations/0002_manual_catalog.sha256",
                "0" * 64 + "\n",
            )
            desktop = root / "src-tauri/src/lib.rs"
            desktop.write_text(
                desktop.read_text(encoding="utf-8")
                + "\n#[tauri::command]\nfn hard_delete_v1() {}\n",
                encoding="utf-8",
            )
            transport = root / "apps/desktop-ui/src/invoke-transport.ts"
            transport.write_text(
                transport.read_text(encoding="utf-8")
                + '\nconst leaked = "__WARDROBE_E2E_TRANSPORT__";\n',
                encoding="utf-8",
            )
            result = p02_manual_catalog.validate_source_contract(root)

        self.assertTrue(result.errors["P02-IMP-001"])
        self.assertTrue(result.errors["P02-DEL-001"])
        self.assertTrue(result.errors["P02-REV-001"])

    def test_accepts_commands_declared_by_the_audited_tauri_macro(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_valid_fixture(root)
            desktop = root / "src-tauri/src/lib.rs"
            commands = p02_manual_catalog.P02_COMMANDS
            invocations = "\n".join(
                f"catalog_command!({command}, handler, Request, Response, method);"
                for command in commands
            )
            desktop.write_text(
                """
macro_rules! catalog_command {
    ($command:ident, $handler:ident, $request:ty, $response:ty, $method:ident) => {
        #[tauri::command]
        fn $command() {}
    };
}
"""
                + invocations,
                encoding="utf-8",
            )

            result = p02_manual_catalog.validate_source_contract(root)

        self.assertEqual(set(commands), set(result.registered_commands))
        self.assertTrue(
            all(not messages for messages in result.errors.values())
        )


class EvaluatorTests(unittest.TestCase):
    @mock.patch(
        "tools.evaluators.p02_manual_catalog.run_bounded_command"
    )
    def test_success_emits_harness_standard_evidence(
        self,
        run: mock.Mock,
    ) -> None:
        run.return_value = command_result()
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_valid_fixture(root)
            evidence = root / "evidence"
            result = p02_manual_catalog.evaluate(
                root,
                evidence,
                set(p02_manual_catalog.REQUIREMENT_IDS),
            )

            self.assertEqual(0, result)
            self.assertEqual(
                len(p02_manual_catalog.COMMAND_CHECKS), run.call_count
            )
            for requirement in p02_manual_catalog.REQUIREMENT_IDS:
                payload = read_json(evidence / f"{requirement}.json")
                self.assertEqual("pass", payload["status"])
                self.assertTrue(payload["test"])
                self.assertTrue(payload["recorded_at"])
                self.assertTrue(
                    payload["details"]["public_summary"]  # type: ignore[index]
                )
                self.assertTrue(
                    all(
                        isinstance(value, (str, int, float, bool))
                        or value is None
                        for value in payload["details"]["public_summary"].values()  # type: ignore[index, union-attr]
                    )
                )
            diagnostics = read_json(
                evidence / p02_manual_catalog.DIAGNOSTICS_NAME
            )
            self.assertEqual("pass", diagnostics["status"])
            self.assertTrue(diagnostics["pass_evidence_written"])
            self.assertNotIn(str(root), json.dumps(diagnostics))
            self.assertTrue(
                all(
                    check.command[0] != "make"
                    for check in p02_manual_catalog.COMMAND_CHECKS
                )
            )

    @mock.patch(
        "tools.evaluators.p02_manual_catalog.run_bounded_command"
    )
    def test_failure_cleans_stale_and_emits_no_partial_pass(
        self,
        run: mock.Mock,
    ) -> None:
        results = [
            command_result()
            for _ in p02_manual_catalog.COMMAND_CHECKS
        ]
        results[2] = command_result(returncode=101)
        run.side_effect = results
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            write_valid_fixture(root)
            evidence = root / "evidence"
            evidence.mkdir()
            for requirement in p02_manual_catalog.REQUIREMENT_IDS:
                write(
                    evidence / f"{requirement}.json",
                    '{"status":"stale"}',
                )

            result = p02_manual_catalog.evaluate(
                root,
                evidence,
                set(p02_manual_catalog.REQUIREMENT_IDS),
            )

            self.assertEqual(1, result)
            self.assertFalse(
                any(
                    (evidence / f"{requirement}.json").exists()
                    for requirement in p02_manual_catalog.REQUIREMENT_IDS
                )
            )
            diagnostics = read_json(
                evidence / p02_manual_catalog.DIAGNOSTICS_NAME
            )
            self.assertEqual("fail", diagnostics["status"])
            self.assertFalse(diagnostics["pass_evidence_written"])

    @mock.patch(
        "tools.evaluators.p02_manual_catalog.run_bounded_command"
    )
    def test_unselected_does_nothing(self, run: mock.Mock) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            result = p02_manual_catalog.evaluate(
                root, root / "evidence", set()
            )
        self.assertEqual(0, result)
        run.assert_not_called()


class DispatcherTests(unittest.TestCase):
    @mock.patch(
        "tools.evaluators.run.p02_manual_catalog.evaluate",
        return_value=0,
    )
    def test_dispatcher_routes_p02_requirements(
        self,
        evaluate: mock.Mock,
    ) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            run_dir = root / "run"
            evidence_dir = root / "evidence"
            run_dir.mkdir()
            selected = ["P02-IMP-001", "P02-REV-001"]
            write(
                run_dir / "requirements.json",
                json.dumps({"selected_requirement_ids": selected}),
            )
            with mock.patch.dict(
                os.environ,
                {
                    "HARNESS_RUN_DIR": str(run_dir),
                    "HARNESS_EVIDENCE_DIR": str(evidence_dir),
                },
            ):
                result = evaluator_run.main()

        self.assertEqual(0, result)
        evaluate.assert_called_once_with(
            evaluator_run.ROOT, evidence_dir, set(selected)
        )


if __name__ == "__main__":
    unittest.main()
