"""Fail-closed evaluator for the approved P05 reconciliation vertical."""

from __future__ import annotations

from dataclasses import dataclass
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import re
import tomllib
from typing import Any

from tools.evaluators.p03_receipts import (
    CommandResult,
    run_bounded_command,
    write_atomic_json,
)


REQUIREMENT_IDS = frozenset(
    {
        "P05-CAN-001",
        "P05-IDN-001",
        "P05-EVD-001",
        "P05-REV-001",
        "P05-DEC-001",
    }
)
RUN_ID = "20260715T055429Z-ecd21f12"
PACKET_DIR = f"artifacts/harness/P05/{RUN_ID}"
STATE_FILE = f"{PACKET_DIR}/state.json"
DIAGNOSTICS_NAME = "p05-reconciliation-diagnostics.json"
MAX_SOURCE_BYTES = 3 * 1024 * 1024
MAX_ARTIFACT_BYTES = 128 * 1024
COMMAND_TIMEOUT_SECONDS = 15 * 60

EXPECTED_PACKET_HASHES = {
    "specs/system.md": "1cb32b71698c8accfafa34dab8c73eb47e047a49ccc6f2ac0b25734e1d8d1546",
    "specs/phases/P05-reconciliation.md": (
        "60ecf992e4e954f00b7fdcf51780c78b510fb66bae1a51f8345a55fab1ba67a9"
    ),
    f"{PACKET_DIR}/requirements.json": (
        "eca96a9af5527cc4694b5d163d14fd70334c1d2d06fae7394f6fb0a6efab440d"
    ),
    f"{PACKET_DIR}/proposal.md": (
        "9bfeef575a5fa1cee7b410f5d79af36f91a676e4b7a083e757756f316c7df80e"
    ),
    f"{PACKET_DIR}/review.md": (
        "053491b91c35b65f18d0d936e9c0ef1a79ee1d26e0a2f226e3b4fc4744d966d2"
    ),
}

RECONCILIATION_COMMANDS = (
    "open_reconciliation_case_v1",
    "decide_reconciliation_case_v1",
    "open_reconciliation_case_v2",
    "decide_reconciliation_case_v2",
    "list_reconciliation_cases_v2",
)
UI_RECONCILIATION_COMMANDS = (
    "open_reconciliation_case_v2",
    "list_reconciliation_cases_v2",
    "decide_reconciliation_case_v2",
)

SOURCE_FILES = (
    "Cargo.lock",
    "crates/wardrobe-core/Cargo.toml",
    "crates/wardrobe-core/src/lib.rs",
    "crates/wardrobe-core/src/catalog.rs",
    "crates/wardrobe-core/src/reconciliation.rs",
    "crates/wardrobe-core/src/ports.rs",
    "crates/wardrobe-core/src/service.rs",
    "crates/wardrobe-core/src/bindings.rs",
    "crates/wardrobe-core/src/bin/generate-bindings.rs",
    "crates/wardrobe-core/tests/reconciliation_contracts.rs",
    "crates/wardrobe-core/tests/reconciliation_service.rs",
    "crates/wardrobe-platform/Cargo.toml",
    "crates/wardrobe-platform/src/lib.rs",
    "crates/wardrobe-platform/src/database.rs",
    "crates/wardrobe-platform/src/catalog_repository.rs",
    "crates/wardrobe-platform/src/reconciliation_repository.rs",
    "crates/wardrobe-platform/src/source_image.rs",
    "crates/wardrobe-platform/migrations/0006_reconciliation.sql",
    "crates/wardrobe-platform/migrations/0006_reconciliation.sha256",
    "crates/wardrobe-platform/tests/reconciliation_repository.rs",
    "src-tauri/Cargo.toml",
    "src-tauri/build.rs",
    "src-tauri/src/lib.rs",
    "src-tauri/capabilities/main.json",
    "src-tauri/permissions/autogenerated/open_reconciliation_case_v1.toml",
    "src-tauri/permissions/autogenerated/decide_reconciliation_case_v1.toml",
    "src-tauri/permissions/autogenerated/open_reconciliation_case_v2.toml",
    "src-tauri/permissions/autogenerated/decide_reconciliation_case_v2.toml",
    "src-tauri/permissions/autogenerated/list_reconciliation_cases_v2.toml",
    "apps/desktop-ui/package.json",
    "apps/desktop-ui/vite.config.ts",
    "apps/desktop-ui/playwright.config.ts",
    "apps/desktop-ui/scripts/check-production-transport.mjs",
    "apps/desktop-ui/src/generated/contracts.ts",
    "apps/desktop-ui/src/invoke-transport.ts",
    "apps/desktop-ui/src/e2e/invoke-transport.ts",
    "apps/desktop-ui/src/reconciliation-bridge.ts",
    "apps/desktop-ui/src/reconciliation-model.ts",
    "apps/desktop-ui/src/ReconciliationPanel.tsx",
    "apps/desktop-ui/src/PhotoAnalysisWorkspace.tsx",
    "apps/desktop-ui/src/App.tsx",
    "apps/desktop-ui/src/reconciliation-bridge.test.ts",
    "apps/desktop-ui/src/reconciliation-model.test.ts",
    "apps/desktop-ui/src/ReconciliationPanel.test.tsx",
    "apps/desktop-ui/src/PhotoAnalysisWorkspace.test.tsx",
    "apps/desktop-ui/e2e/reconciliation.spec.ts",
)

PRODUCTION_RECONCILIATION_FILES = (
    "crates/wardrobe-core/src/reconciliation.rs",
    "crates/wardrobe-platform/src/reconciliation_repository.rs",
    "crates/wardrobe-platform/src/source_image.rs",
    "apps/desktop-ui/src/reconciliation-bridge.ts",
    "apps/desktop-ui/src/reconciliation-model.ts",
    "apps/desktop-ui/src/ReconciliationPanel.tsx",
)


@dataclass(frozen=True)
class CommandCheck:
    name: str
    command: tuple[str, ...]
    require_rust_test: bool = False


COMMAND_CHECKS = (
    CommandCheck(
        "core_reconciliation",
        (
            "cargo",
            "test",
            "--offline",
            "-p",
            "wardrobe-core",
            "--test",
            "reconciliation_contracts",
            "--test",
            "reconciliation_service",
        ),
        require_rust_test=True,
    ),
    CommandCheck(
        "migration_v6_database",
        (
            "cargo",
            "test",
            "--offline",
            "-p",
            "wardrobe-platform",
            "--lib",
            "database::tests",
        ),
        require_rust_test=True,
    ),
    CommandCheck(
        "platform_reconciliation_repository",
        (
            "cargo",
            "test",
            "--offline",
            "-p",
            "wardrobe-platform",
            "--test",
            "reconciliation_repository",
        ),
        require_rust_test=True,
    ),
    CommandCheck(
        "desktop_reconciliation",
        (
            "cargo",
            "test",
            "--offline",
            "-p",
            "wardrobe-desktop",
            "reconciliation_commands_use_real_local_state_for_all_outcomes_and_restart_replay",
        ),
        require_rust_test=True,
    ),
    CommandCheck(
        "reconciliation_bindings_drift",
        (
            "cargo",
            "test",
            "--offline",
            "-p",
            "wardrobe-core",
            "generated_bindings_are_current",
        ),
        require_rust_test=True,
    ),
    CommandCheck(
        "ui_reconciliation",
        (
            "npm",
            "--workspace",
            "@wardrobe/desktop-ui",
            "test",
            "--",
            "src/reconciliation-bridge.test.ts",
            "src/reconciliation-model.test.ts",
            "src/ReconciliationPanel.test.tsx",
            "src/PhotoAnalysisWorkspace.test.tsx",
        ),
    ),
    CommandCheck(
        "ui_production_build",
        ("npm", "--workspace", "@wardrobe/desktop-ui", "run", "build"),
    ),
    CommandCheck(
        "production_transport_exclusion",
        (
            "npm",
            "--workspace",
            "@wardrobe/desktop-ui",
            "run",
            "check:production-transport",
        ),
    ),
    CommandCheck(
        "reconciliation_playwright",
        (
            "npm",
            "--workspace",
            "@wardrobe/desktop-ui",
            "run",
            "test:e2e",
            "--",
            "reconciliation.spec.ts",
        ),
    ),
)


@dataclass(frozen=True)
class PacketValidation:
    errors: tuple[str, ...]
    packet_sha256: str
    hashes: dict[str, str]


@dataclass(frozen=True)
class SourceValidation:
    errors: tuple[str, ...]
    source_sha256: str
    migration_sha256: str
    registered_commands: tuple[str, ...]
    acl_permissions: tuple[str, ...]
    schema_tables: tuple[str, ...]
    production_local_only: bool
    automatic_acceptance_disabled: bool
    deletion_targets_unchanged: bool
    production_transport_isolated: bool
    playwright_specs: tuple[str, ...]


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def _read_bounded(path: Path) -> bytes | None:
    try:
        with path.open("rb") as handle:
            data = handle.read(MAX_SOURCE_BYTES + 1)
    except OSError:
        return None
    return data if len(data) <= MAX_SOURCE_BYTES else None


def _json_object(data: bytes | str) -> dict[str, Any]:
    try:
        value = json.loads(data)
    except (json.JSONDecodeError, UnicodeDecodeError, TypeError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def _toml_object(text: str) -> dict[str, Any]:
    try:
        value = tomllib.loads(text)
    except (tomllib.TOMLDecodeError, ValueError):
        return {}
    return value if isinstance(value, dict) else {}


def validate_packet(root: Path) -> PacketValidation:
    errors: list[str] = []
    hashes: dict[str, str] = {}
    aggregate = hashlib.sha256()
    contents: dict[str, bytes] = {}
    for relative, expected_hash in EXPECTED_PACKET_HASHES.items():
        data = _read_bounded(root / relative)
        if data is None:
            errors.append(f"frozen packet file is unreadable or oversized: {relative}")
            continue
        actual_hash = hashlib.sha256(data).hexdigest()
        hashes[relative] = actual_hash
        contents[relative] = data
        if actual_hash != expected_hash:
            errors.append(f"frozen packet hash changed: {relative}")
        aggregate.update(relative.encode("utf-8"))
        aggregate.update(b"\0")
        aggregate.update(data)
        aggregate.update(b"\0")

    state_data = _read_bounded(root / STATE_FILE)
    if state_data is None:
        errors.append(f"mutable harness state is unreadable or oversized: {STATE_FILE}")
    else:
        hashes[STATE_FILE] = hashlib.sha256(state_data).hexdigest()
        contents[STATE_FILE] = state_data

    requirements = _json_object(
        contents.get(f"{PACKET_DIR}/requirements.json", b"")
    )
    state = _json_object(contents.get(STATE_FILE, b""))
    selected = requirements.get("selected_requirement_ids")
    requirement_rows = requirements.get("requirements")
    evidenced = (
        {
            row.get("id")
            for row in requirement_rows
            if isinstance(row, dict) and row.get("evidence_required") is True
        }
        if isinstance(requirement_rows, list)
        else set()
    )
    if (
        requirements.get("phase") != "P05"
        or requirements.get("git_revision")
        != "8a8d99f2f6313a11d12cc1aefcf45dd2789614f8"
        or not isinstance(selected, list)
        or set(selected) != REQUIREMENT_IDS
        or len(selected) != len(REQUIREMENT_IDS)
        or evidenced != REQUIREMENT_IDS
    ):
        errors.append("frozen P05 requirement selection is invalid")

    review = state.get("review")
    spec_hashes = state.get("spec_hashes")
    if (
        state.get("phase") != "P05"
        or state.get("run_id") != RUN_ID
        or state.get("status") not in {"APPROVED", "BUILT", "EVALUATED"}
        or state.get("selected_requirement_ids") != selected
        or not isinstance(review, dict)
        or review.get("decision") != "APPROVE"
        or review.get("proposal_hash")
        != EXPECTED_PACKET_HASHES[f"{PACKET_DIR}/proposal.md"]
        or not isinstance(review.get("reviewer"), str)
        or not review.get("reviewer")
        or spec_hashes
        != {
            "specs/phases/P05-reconciliation.md": EXPECTED_PACKET_HASHES[
                "specs/phases/P05-reconciliation.md"
            ],
            "specs/system.md": EXPECTED_PACKET_HASHES["specs/system.md"],
        }
    ):
        errors.append("approved P05 state or independent review is invalid")
    if state.get("status") in {"BUILT", "EVALUATED"}:
        build = state.get("build")
        if (
            not isinstance(build, dict)
            or build.get("exit_code") != 0
            or not isinstance(build.get("source_fingerprint"), str)
            or len(build.get("source_fingerprint", "")) != 64
        ):
            errors.append("P05 harness build record is missing or invalid")

    review_text = contents.get(f"{PACKET_DIR}/review.md", b"").decode(
        "utf-8", errors="replace"
    )
    if "Status: APPROVED" not in review_text or "\nAPPROVE\n" not in review_text:
        errors.append("approved P05 review decision is missing")

    return PacketValidation(
        errors=tuple(dict.fromkeys(errors)),
        packet_sha256=aggregate.hexdigest(),
        hashes=hashes,
    )


def _read_sources(root: Path) -> tuple[dict[str, bytes], list[str], str]:
    sources: dict[str, bytes] = {}
    errors: list[str] = []
    digest = hashlib.sha256()
    for relative in SOURCE_FILES:
        data = _read_bounded(root / relative)
        if data is None:
            errors.append(f"required P05 file is unreadable or oversized: {relative}")
            continue
        sources[relative] = data
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(data)
        digest.update(b"\0")
    return sources, errors, digest.hexdigest()


def _text(sources: dict[str, bytes], relative: str) -> str:
    try:
        return sources[relative].decode("utf-8")
    except (KeyError, UnicodeDecodeError):
        return ""


def _block(text: str, start: str, end: str) -> str:
    start_index = text.find(start)
    if start_index < 0:
        return ""
    end_index = text.find(end, start_index + len(start))
    return text[start_index:] if end_index < 0 else text[start_index:end_index]


def _reconciliation_commands(text: str) -> tuple[str, ...]:
    return tuple(
        dict.fromkeys(
            re.findall(
                r"\b[a-z][a-z0-9_]*reconciliation[a-z0-9_]*_v[12]\b",
                text,
            )
        )
    )


def validate_source_contract(root: Path) -> SourceValidation:
    sources, errors, source_sha256 = _read_sources(root)
    reconciliation = _text(
        sources, "crates/wardrobe-core/src/reconciliation.rs"
    )
    catalog = _text(sources, "crates/wardrobe-core/src/catalog.rs")
    ports = _text(sources, "crates/wardrobe-core/src/ports.rs")
    service = _text(sources, "crates/wardrobe-core/src/service.rs")
    bindings = _text(sources, "crates/wardrobe-core/src/bindings.rs")
    generator = _text(
        sources, "crates/wardrobe-core/src/bin/generate-bindings.rs"
    )
    generated = _text(sources, "apps/desktop-ui/src/generated/contracts.ts")
    platform_lib = _text(sources, "crates/wardrobe-platform/src/lib.rs")
    database = _text(sources, "crates/wardrobe-platform/src/database.rs")
    deletion = _text(
        sources, "crates/wardrobe-platform/src/catalog_repository.rs"
    )
    repository = _text(
        sources, "crates/wardrobe-platform/src/reconciliation_repository.rs"
    )
    source_image = _text(
        sources, "crates/wardrobe-platform/src/source_image.rs"
    )
    desktop = _text(sources, "src-tauri/src/lib.rs")
    build_rs = _text(sources, "src-tauri/build.rs")
    bridge = _text(sources, "apps/desktop-ui/src/reconciliation-bridge.ts")
    model = _text(sources, "apps/desktop-ui/src/reconciliation-model.ts")
    panel = _text(sources, "apps/desktop-ui/src/ReconciliationPanel.tsx")
    workspace = _text(sources, "apps/desktop-ui/src/PhotoAnalysisWorkspace.tsx")
    panel_test = _text(
        sources, "apps/desktop-ui/src/ReconciliationPanel.test.tsx"
    )
    e2e = _text(sources, "apps/desktop-ui/e2e/reconciliation.spec.ts")

    core_markers = (
        "IdentityRelationV1",
        "VisualSimilarity",
        "SameProductVariant",
        "SamePhysicalItem",
        "CandidateEvidencePolarityV1",
        "Supporting",
        "Contradictory",
        "Neutral",
        "ReconciliationCandidateTargetV1",
        "NoMatch",
        "ReconciliationOutcomeV1",
        "SameItem",
        "SameVariant",
        "Different",
        "Unresolved",
        "no_match_count != 1",
        "validate_for_case",
    )
    if (
        not all(marker in reconciliation for marker in core_markers)
        or reconciliation.count("deny_unknown_fields") < 7
        or "pub trait ReconciliationPort" not in ports
        or not all(command in service for command in RECONCILIATION_COMMANDS)
        or "mod reconciliation;" not in _text(
            sources, "crates/wardrobe-core/src/lib.rs"
        )
    ):
        errors.append("P05 core contracts, evidence, or decision rules are incomplete")

    generated_markers = (
        'export type IdentityRelationV1 = "visual_similarity" | '
        '"same_product_variant" | "same_physical_item";',
        'export type CandidateEvidencePolarityV1 = "supporting" | '
        '"contradictory" | "neutral";',
        'export type ReconciliationOutcomeV1 = "same_item" | "same_variant" | '
        '"different" | "no_match" | "unresolved";',
        "OpenReconciliationCaseV1Request",
        "DecideReconciliationCaseV1Request",
        "CandidateEvidenceV1",
        "ReconciliationCaseV1",
    )
    if not (
        "generated_bindings_are_current" in bindings
        and "typescript_bindings" in generator
        and "// @generated by wardrobe-core." in generated
        and all(marker in generated for marker in generated_markers)
        and all(
            marker in bindings
            for marker in (
                "IdentityRelationV1::decl()",
                "CandidateEvidenceV1::decl()",
                "OpenReconciliationCaseV1Request::decl()",
                "DecideReconciliationCaseV1Response::decl()",
            )
        )
    ):
        errors.append("P05 generated TypeScript bindings are incomplete")

    sql_name = "crates/wardrobe-platform/migrations/0006_reconciliation.sql"
    checksum_name = (
        "crates/wardrobe-platform/migrations/0006_reconciliation.sha256"
    )
    sql = sources.get(sql_name, b"")
    sql_text = sql.decode("utf-8", errors="replace")
    migration_sha256 = hashlib.sha256(sql).hexdigest()
    recorded_checksum = _text(sources, checksum_name).strip()
    schema_tables = (
        "reconciliation_cases",
        "reconciliation_candidates",
        "reconciliation_candidate_evidence",
        "reconciliation_evidence_input_hashes",
        "reconciliation_decisions",
        "reconciliation_decision_heads",
        "reconciliation_command_entities",
    )
    ordered_versions = [database.find(f"version: {version}") for version in range(1, 7)]
    schema_markers = (
        "target_kind IN ('no_match', 'wardrobe_item', 'receipt_line')",
        "'visual_similarity', 'same_product_variant',",
        "'same_item', 'same_variant', 'different',",
        "reconciliation_candidates_no_match_idx",
        "reconciliation_decisions_no_update",
        "reconciliation_cases_no_delete",
    )
    if (
        not sql
        or recorded_checksum != migration_sha256
        or re.fullmatch(r"[0-9a-f]{64}", recorded_checksum) is None
        or min(ordered_versions) < 0
        or ordered_versions != sorted(ordered_versions)
        or 'include_str!("../migrations/0006_reconciliation.sql")' not in database
        or 'include_str!("../migrations/0006_reconciliation.sha256")' not in database
        or "version: 6" not in database
        or sql_text.count("ADD COLUMN reconciliation_revision") != 2
        or any(
            f"CREATE TABLE {table}" not in sql_text
            for table in schema_tables
        )
        or not all(marker in sql_text for marker in schema_markers)
    ):
        errors.append("checksummed ordered v6 reconciliation schema is incomplete")

    repository_markers = (
        "impl ReconciliationPort for Database",
        "TransactionBehavior::Immediate",
        "advance_reconciliation_revision",
        "reconciliation_command_entities",
        "command_receipts",
        "CorrectedReceiptOrderV1",
        "reviewed_order_json",
        "BlobStore",
        "extract_local_visual_features_v1",
        "augment_reconciliation_deletion_closure",
    )
    source_image_markers = (
        "canonical_rgba8",
        "into_rgba8",
        "imageops::FilterType::Triangle",
        "sample * alpha + 255 * (255 - alpha) + 127",
        "77 * red + 150 * green + 29 * blue + 128",
        "1_u64 << (y * 8 + x)",
        "(sum + 36) / 72",
    )
    deletion_markers = (
        "augment_reconciliation_deletion_closure",
        "reconciliation_revision",
        "connection.transaction()?",
        "snapshot_expired",
        "classified_reconciliation_tables",
    )
    if not (
        "mod reconciliation_repository;" in platform_lib
        and "mod source_image;" in platform_lib
        and all(marker in repository for marker in repository_markers)
        and all(marker in source_image for marker in source_image_markers)
        and all(marker in deletion for marker in deletion_markers)
    ):
        errors.append(
            "P05 repository, fixed local extractor, replay, or deletion closure is incomplete"
        )

    target_block = _block(
        catalog,
        "pub enum DeletionTargetKindV1 {",
        "\n}",
    )
    target_variants = tuple(
        re.findall(r"(?m)^\s{4}([A-Za-z][A-Za-z0-9_]*)\s*,\s*$", target_block)
    )
    deletion_targets_unchanged = (
        target_variants
        == (
            "ImportRoot",
            "Source",
            "Item",
            "PhotoKitEnrollment",
            "PhotoKitAsset",
        )
        and (
            'export type DeletionTargetKindV1 = "import_root" | "source" | '
            '"item" | "photokit_enrollment" | "photokit_asset";'
        )
        in generated
        and "DeletionTargetKindV1::ImportRoot => \"import_root\"" in deletion
        and "DeletionTargetKindV1::Source => \"source\"" in deletion
        and "DeletionTargetKindV1::Item => \"item\"" in deletion
        and (
            "DeletionTargetKindV1::PhotoKitEnrollment => "
            '"photokit_enrollment"'
        )
        in deletion
        and "DeletionTargetKindV1::PhotoKitAsset => \"photokit_asset\"" in deletion
    )
    if not deletion_targets_unchanged:
        errors.append("P05 added or changed a deletion target kind")

    desktop_production = desktop.split("#[cfg(test)]", 1)[0]
    handler_block = _block(
        desktop_production,
        ".invoke_handler(tauri::generate_handler![",
        "])",
    )
    registered_commands = tuple(
        command
        for command in RECONCILIATION_COMMANDS
        if command in handler_block
    )
    build_commands = _reconciliation_commands(build_rs)
    handler_commands = _reconciliation_commands(handler_block)
    capability = _json_object(
        sources.get("src-tauri/capabilities/main.json", b"")
    )
    permissions = capability.get("permissions")
    acl_permissions = (
        tuple(
            permission
            for permission in permissions
            if isinstance(permission, str) and "reconciliation" in permission
        )
        if isinstance(permissions, list)
        else ()
    )
    expected_permissions = tuple(
        "allow-" + command.replace("_", "-")
        for command in RECONCILIATION_COMMANDS
    )
    command_surface_valid = (
        build_commands == RECONCILIATION_COMMANDS
        and handler_commands == RECONCILIATION_COMMANDS
        and registered_commands == RECONCILIATION_COMMANDS
        and acl_permissions == expected_permissions
    )
    for command in RECONCILIATION_COMMANDS:
        permission_name = (
            f"src-tauri/permissions/autogenerated/{command}.toml"
        )
        permission = _toml_object(_text(sources, permission_name))
        allow = permission.get("permission")
        allow_rows = allow if isinstance(allow, list) else []
        allow_entry = next(
            (
                row
                for row in allow_rows
                if isinstance(row, dict)
                and row.get("identifier")
                == "allow-" + command.replace("_", "-")
            ),
            None,
        )
        commands = allow_entry.get("commands") if isinstance(allow_entry, dict) else None
        if (
            command not in desktop_production
            or not isinstance(commands, dict)
            or commands.get("allow") != [command]
        ):
            command_surface_valid = False
    if not command_surface_valid:
        errors.append("the approved P05 and owner-authority Tauri ACLs are required")

    production_text_parts: list[str] = []
    for relative in PRODUCTION_RECONCILIATION_FILES:
        text = _text(sources, relative)
        if relative.endswith(".rs"):
            text = text.split("#[cfg(test)]", 1)[0]
        production_text_parts.append(text)
    production_text = "\n".join(production_text_parts)
    forbidden_production_patterns = (
        r"\b(?:reqwest|ureq|hyper)::",
        r"\b(?:TcpStream|WebSocket)\b",
        r"\b(?:std|tokio)::net\b",
        r"\b(?:CredentialPort|Keychain|api_key)\b",
        r"\b(?:Mock|Scripted|Fake)[A-Za-z0-9_]*\b",
        r"\btrait\s+[A-Za-z0-9_]*Provider\b",
        r"\bwith_[a-z0-9_]*provider\b",
        r"\bfetch\s*\(",
        r"https?://",
        r"\b(?:model_url|model_path|candle_|hf_hub|ort::|tch::|tract_onnx)\b",
    )
    production_local_only = (
        not any(
            re.search(pattern, production_text, flags=re.IGNORECASE)
            for pattern in forbidden_production_patterns
        )
        and _reconciliation_commands(bridge) == UI_RECONCILIATION_COMMANDS
        and all(
            bridge.count(f'"{command}"') == 1
            for command in UI_RECONCILIATION_COMMANDS
        )
        and "productionInvoke" in bridge
        and re.search(r"\bretr(?:y|ies|ied|ying)\b", bridge, re.IGNORECASE)
        is None
    )
    if not production_local_only:
        errors.append(
            "P05 production path contains a model, provider, network, credential, mock, or retry path"
        )

    automatic_acceptance_disabled = not re.search(
        r"(?i)(auto(?:matic)?[_ -]?(?:accept|decision)|"
        r"calibrated[_ -]?(?:score|confidence|probability)|"
        r"(?:acceptance|decision)[_ -]?(?:confidence|probability))",
        production_text,
    )
    if not automatic_acceptance_disabled:
        errors.append(
            "P05 production adds automatic acceptance, calibration, confidence, or history"
        )

    production_transport = _text(
        sources, "apps/desktop-ui/src/invoke-transport.ts"
    )
    e2e_transport = _text(
        sources, "apps/desktop-ui/src/e2e/invoke-transport.ts"
    )
    vite_config = _text(sources, "apps/desktop-ui/vite.config.ts")
    transport_check = _text(
        sources, "apps/desktop-ui/scripts/check-production-transport.mjs"
    )
    production_transport_isolated = (
        "@tauri-apps/api/core" in production_transport
        and "__WARDROBE_E2E_TRANSPORT__" not in production_transport
        and "__WARDROBE_E2E_TRANSPORT__" in e2e_transport
        and "__WARDROBE_E2E_TRANSPORT__" not in bridge
        and "__WARDROBE_E2E_TRANSPORT__" not in panel
        and "__WARDROBE_E2E_TRANSPORT__" not in workspace
        and "WARDROBE_E2E" in vite_config
        and "./src/e2e/invoke-transport.ts" in vite_config
        and "./src/invoke-transport.ts" in vite_config
        and "__WARDROBE_E2E_TRANSPORT__" in transport_check
    )
    if not production_transport_isolated:
        errors.append("production transport includes the P05 e2e transport")

    ui_markers = (
        "Supporting",
        "Contradictory",
        "Neutral",
        "Same wardrobe item",
        "Same product variant",
        "Different",
        "No match",
        "Unresolved",
    )
    if not (
        all(marker in model for marker in ui_markers)
        and "leading_candidate_id" in model
        and "Date unknown" in model
        and "reconciliation-decision-summary" in panel
        and "Find local matches" in workspace
        and "ReconciliationPanel" in workspace
        and "records all five outcomes" in panel_test
        and "AxeBuilder" in e2e
        and "remoteRequests" in e2e
        and len(re.findall(r"(?m)^\s*test\s*\(", e2e)) == 1
    ):
        errors.append("P05 production bridge, review UI, or focused smoke is incomplete")

    try:
        playwright_specs = tuple(
            sorted(
                path.relative_to(root).as_posix()
                for path in (root / "apps/desktop-ui/e2e").glob(
                    "*reconciliation*.spec.ts"
                )
                if path.is_file()
            )
        )
    except OSError:
        playwright_specs = ()
    if playwright_specs != ("apps/desktop-ui/e2e/reconciliation.spec.ts",):
        errors.append("exactly one reconciliation Playwright spec is required")

    return SourceValidation(
        errors=tuple(dict.fromkeys(errors)),
        source_sha256=source_sha256,
        migration_sha256=migration_sha256,
        registered_commands=registered_commands,
        acl_permissions=acl_permissions,
        schema_tables=schema_tables,
        production_local_only=production_local_only,
        automatic_acceptance_disabled=automatic_acceptance_disabled,
        deletion_targets_unchanged=deletion_targets_unchanged,
        production_transport_isolated=production_transport_isolated,
        playwright_specs=playwright_specs,
    )


def _result_summary(result: CommandResult) -> dict[str, Any]:
    return {
        "returncode": result.returncode,
        "output_sha256": result.output_sha256,
        "output_bytes": result.output_bytes,
        "duration_ms": result.duration_ms,
        "timed_out": result.timed_out,
        "output_limit_exceeded": result.output_limit_exceeded,
        "launch_failed": result.launch_failed,
    }


def _command_error(check: CommandCheck, result: CommandResult) -> str | None:
    if result.launch_failed:
        return f"{check.name} could not launch"
    if result.timed_out:
        return f"{check.name} timed out"
    if result.output_limit_exceeded:
        return f"{check.name} exceeded its output bound"
    if result.returncode != 0:
        return f"{check.name} failed"
    if check.require_rust_test:
        output = result.captured_output.decode("utf-8", errors="replace")
        counts = [
            int(value)
            for value in re.findall(r"\brunning\s+(\d+)\s+tests?\b", output)
        ]
        if not counts or max(counts) < 1:
            return f"{check.name} matched no Rust tests"
    return None


def _remove_stale_outputs(evidence_dir: Path) -> None:
    for requirement in REQUIREMENT_IDS:
        (evidence_dir / f"{requirement}.json").unlink(missing_ok=True)
    (evidence_dir / DIAGNOSTICS_NAME).unlink(missing_ok=True)


def _bounded_json_bytes(value: dict[str, Any]) -> bytes:
    data = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    if len(data) > MAX_ARTIFACT_BYTES:
        raise ValueError("P05 evaluator artifact exceeds size limit")
    return data


def _write_bounded_json(path: Path, value: dict[str, Any]) -> None:
    _bounded_json_bytes(value)
    write_atomic_json(path, value)


def _verification_hash(
    requirement: str,
    packet: PacketValidation,
    source: SourceValidation,
    checks: dict[str, dict[str, Any]],
) -> str:
    value = {
        "requirement_id": requirement,
        "packet_sha256": packet.packet_sha256,
        "source_sha256": source.source_sha256,
        "migration_sha256": source.migration_sha256,
        "checks": checks,
    }
    return hashlib.sha256(_bounded_json_bytes(value)).hexdigest()


def _diagnostics(
    *,
    requested: set[str],
    failures: list[str],
    packet: PacketValidation,
    source: SourceValidation | None,
    checks: dict[str, dict[str, Any]],
    generated_at: str,
    pass_evidence_written: bool,
) -> dict[str, Any]:
    return {
        "schema_version": 1,
        "status": "fail" if failures else "pass",
        "generated_at": generated_at,
        "selected_requirement_ids": sorted(requested),
        "failures": failures,
        "packet_sha256": packet.packet_sha256,
        "packet_hashes": packet.hashes,
        "source_sha256": source.source_sha256 if source else "",
        "migration_sha256": source.migration_sha256 if source else "",
        "registered_commands": list(source.registered_commands) if source else [],
        "acl_permissions": list(source.acl_permissions) if source else [],
        "schema_tables": list(source.schema_tables) if source else [],
        "production_local_only": source.production_local_only if source else False,
        "automatic_acceptance_disabled": (
            source.automatic_acceptance_disabled if source else False
        ),
        "deletion_targets_unchanged": (
            source.deletion_targets_unchanged if source else False
        ),
        "production_transport_isolated": (
            source.production_transport_isolated if source else False
        ),
        "playwright_specs": list(source.playwright_specs) if source else [],
        "checks": checks,
        "deferred_limitations": [
            "model adjudication and provider credentials are deferred",
            "automatic acceptance and calibration claims are deferred",
            "notarization and clean-machine certification are deferred",
        ],
        "pass_evidence_written": pass_evidence_written,
    }


def evaluate(root: Path, evidence_dir: Path, selected: set[str]) -> int:
    requested = selected & REQUIREMENT_IDS
    if not requested:
        return 0

    evidence_dir.mkdir(parents=True, exist_ok=True)
    _remove_stale_outputs(evidence_dir)
    generated_at = utc_now()
    packet = validate_packet(root)
    source: SourceValidation | None = None
    checks: dict[str, dict[str, Any]] = {}
    failures = list(packet.errors)
    if selected != set(REQUIREMENT_IDS):
        failures.append("selected P05 requirement IDs must exactly match the approved set")

    if not failures:
        source = validate_source_contract(root)
        failures.extend(source.errors)

    if not failures:
        assert source is not None
        environment = os.environ.copy()
        environment.pop("HARNESS_RUN_DIR", None)
        environment.pop("HARNESS_EVIDENCE_DIR", None)
        for check in COMMAND_CHECKS:
            result = run_bounded_command(
                list(check.command),
                cwd=root,
                env=environment,
                timeout_seconds=COMMAND_TIMEOUT_SECONDS,
                capture_output=check.require_rust_test,
            )
            checks[check.name] = _result_summary(result)
            error = _command_error(check, result)
            if error:
                failures.append(error)
                break

    if failures or source is None:
        diagnostics = _diagnostics(
            requested=requested,
            failures=list(dict.fromkeys(failures)),
            packet=packet,
            source=source,
            checks=checks,
            generated_at=generated_at,
            pass_evidence_written=False,
        )
        _write_bounded_json(evidence_dir / DIAGNOSTICS_NAME, diagnostics)
        return 1

    payloads: dict[str, dict[str, Any]] = {}
    for requirement in sorted(requested):
        payloads[requirement] = {
            "schema_version": 1,
            "requirement_id": requirement,
            "status": "pass",
            "test": "p05_reconciliation::focused_production_verification",
            "recorded_at": generated_at,
            "details": {
                "evaluator": "tools/evaluators/p05_reconciliation.py",
                "verification_sha256": _verification_hash(
                    requirement, packet, source, checks
                ),
                "checks": list(checks),
                "public_summary": {
                    "profile": "personal_mvp",
                    "packet_sha256": packet.packet_sha256,
                    "source_sha256": source.source_sha256,
                    "migration_sha256": source.migration_sha256,
                    "model_adjudication": "deferred",
                    "calibration_and_automatic_acceptance": "deferred",
                    "provider_credentials": "deferred",
                    "notarization": "deferred",
                    "clean_machine_certification": "deferred",
                },
            },
        }
        _bounded_json_bytes(payloads[requirement])

    diagnostics = _diagnostics(
        requested=requested,
        failures=[],
        packet=packet,
        source=source,
        checks=checks,
        generated_at=generated_at,
        pass_evidence_written=True,
    )
    _bounded_json_bytes(diagnostics)
    written: list[Path] = []
    try:
        for requirement, payload in payloads.items():
            path = evidence_dir / f"{requirement}.json"
            _write_bounded_json(path, payload)
            written.append(path)
        _write_bounded_json(evidence_dir / DIAGNOSTICS_NAME, diagnostics)
    except BaseException:
        for path in written:
            path.unlink(missing_ok=True)
        (evidence_dir / DIAGNOSTICS_NAME).unlink(missing_ok=True)
        raise
    return 0
