"""Fail-closed evaluator for the approved P09 diagnostics-export packet."""

from __future__ import annotations

from dataclasses import dataclass
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any

from tools.evaluators.p03_receipts import (
    CommandResult,
    run_bounded_command,
    write_atomic_json,
)


SYSTEM_REQUIREMENT_IDS = frozenset(
    {
        "SYS-ARC-001",
        "SYS-DAT-001",
        "SYS-DAT-002",
        "SYS-DEC-001",
        "SYS-REL-001",
        "SYS-REL-002",
        "SYS-SEC-001",
        "SYS-SEC-002",
        "SYS-PRV-001",
        "SYS-OBS-001",
        "SYS-DEL-001",
        "SYS-UPG-001",
        "SYS-A11Y-001",
    }
)
TRIGGER_REQUIREMENT_IDS = frozenset({"P09-DIA-001"})
REQUIREMENT_IDS = SYSTEM_REQUIREMENT_IDS | TRIGGER_REQUIREMENT_IDS
DEFERRED_REQUIREMENT_IDS = frozenset(
    {"SYS-REL-002", "SYS-SEC-002", "SYS-A11Y-001"}
)

RUN_ID = "20260715T181740Z-9ea04245"
PACKET_DIR = f"artifacts/harness/P09/{RUN_ID}"
DIAGNOSTICS_NAME = "p09-diagnostics-evaluator.json"
MAX_SOURCE_BYTES = 4 * 1024 * 1024
MAX_ARTIFACT_BYTES = 128 * 1024
COMMAND_TIMEOUT_SECONDS = 20 * 60

EXPECTED_PACKET_HASHES = {
    "specs/system.md": (
        "1cb32b71698c8accfafa34dab8c73eb47e047a49ccc6f2ac0b25734e1d8d1546"
    ),
    "specs/phases/P09-hardening.md": (
        "b88c11b3f97bf7936f19cc6f6e187268eeb0c6a6c11f12de17ed2edf36455846"
    ),
    f"{PACKET_DIR}/requirements.json": (
        "e65221327beb569a51da0b601e5a4364c5ab6c1fe020a463489323908857dff7"
    ),
    f"{PACKET_DIR}/proposal.md": (
        "5f8dd85658478d7320bf16725e091f9e21b6878666ce6aecaf2c4632f0764cea"
    ),
    f"{PACKET_DIR}/review.md": (
        "517f4f4cb9e71d1da59242563d362b4d36dea42f736ea11e8dc76b6252c07a66"
    ),
}

SOURCE_FILES = (
    "Cargo.toml",
    "Cargo.lock",
    "crates/wardrobe-core/Cargo.toml",
    "crates/wardrobe-core/src/bindings.rs",
    "crates/wardrobe-core/src/contracts.rs",
    "crates/wardrobe-core/src/diagnostics_backend.rs",
    "crates/wardrobe-core/src/lib.rs",
    "crates/wardrobe-core/tests/diagnostics_export_contracts.rs",
    "crates/wardrobe-platform/src/backup_repository.rs",
    "crates/wardrobe-platform/src/database.rs",
    "crates/wardrobe-platform/src/diagnostics.rs",
    "crates/wardrobe-platform/src/diagnostics_export.rs",
    "crates/wardrobe-platform/src/lib.rs",
    "src-tauri/Cargo.toml",
    "src-tauri/build.rs",
    "src-tauri/capabilities/main.json",
    "src-tauri/permissions/autogenerated/export_diagnostics_v1.toml",
    "src-tauri/src/lib.rs",
    "apps/desktop-ui/package.json",
    "apps/desktop-ui/src/diagnostics-bridge.ts",
    "apps/desktop-ui/src/diagnostics-bridge.test.ts",
    "apps/desktop-ui/src/DiagnosticsSettings.tsx",
    "apps/desktop-ui/src/DiagnosticsSettings.test.tsx",
    "apps/desktop-ui/src/generated/contracts.ts",
)

FORBIDDEN_SOURCE_TERMS = (
    "DiagnosticsPublicationStatusV1",
    "DiagnosticsFailureAggregateV1",
    "DiagnosticsEventCounterV1",
    "DiagnosticsSubsystemV1",
    "DiagnosticsOperationKindV1",
    "published_durability_uncertain",
)


@dataclass(frozen=True)
class PacketValidation:
    errors: tuple[str, ...]
    sha256: str


@dataclass(frozen=True)
class SourceValidation:
    errors: tuple[str, ...]
    sha256: str
    file_count: int


@dataclass(frozen=True)
class CommandCheck:
    name: str
    command: tuple[str, ...]
    compiled_smoke: bool = False


COMMAND_CHECKS = (
    CommandCheck(
        "core_contracts",
        (
            "cargo",
            "test",
            "-p",
            "wardrobe-core",
            "--offline",
            "--test",
            "diagnostics_export_contracts",
        ),
    ),
    CommandCheck(
        "platform_diagnostics",
        (
            "cargo",
            "test",
            "-p",
            "wardrobe-platform",
            "--offline",
            "diagnostics",
            "--lib",
            "--",
            "--test-threads=1",
        ),
    ),
    CommandCheck(
        "desktop_diagnostics_smoke",
        (
            "cargo",
            "test",
            "-p",
            "wardrobe-desktop",
            "--offline",
            "diagnostics_export_uses_real_sqlite_log_and_atomic_filesystem_path",
            "--",
            "--nocapture",
        ),
        compiled_smoke=True,
    ),
    CommandCheck(
        "desktop_ui_diagnostics",
        (
            "npm",
            "test",
            "--workspace",
            "@wardrobe/desktop-ui",
            "--",
            "--run",
            "src/diagnostics-bridge.test.ts",
            "src/DiagnosticsSettings.test.tsx",
        ),
    ),
    CommandCheck(
        "desktop_ui_production_build",
        ("npm", "run", "build", "--workspace", "@wardrobe/desktop-ui"),
    ),
)


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat()


def _read(path: Path) -> bytes | None:
    try:
        data = path.read_bytes()
    except OSError:
        return None
    return data if len(data) <= MAX_SOURCE_BYTES else None


def _aggregate_hash(contents: dict[str, bytes]) -> str:
    digest = hashlib.sha256()
    for name, data in sorted(contents.items()):
        digest.update(name.encode())
        digest.update(b"\0")
        digest.update(data)
        digest.update(b"\0")
    return digest.hexdigest()


def validate_packet(root: Path) -> PacketValidation:
    errors: list[str] = []
    contents: dict[str, bytes] = {}
    for relative, expected in EXPECTED_PACKET_HASHES.items():
        data = _read(root / relative)
        if data is None:
            errors.append(f"packet file unreadable or oversized: {relative}")
            continue
        contents[relative] = data
        if hashlib.sha256(data).hexdigest() != expected:
            errors.append(f"packet hash mismatch: {relative}")
    return PacketValidation(tuple(errors), _aggregate_hash(contents))


def validate_source(root: Path) -> SourceValidation:
    errors: list[str] = []
    contents: dict[str, bytes] = {}
    text_by_name: dict[str, str] = {}
    for relative in SOURCE_FILES:
        data = _read(root / relative)
        if data is None:
            errors.append(f"source file unreadable or oversized: {relative}")
            continue
        contents[relative] = data
        try:
            text_by_name[relative] = data.decode()
        except UnicodeDecodeError:
            errors.append(f"source file is not UTF-8: {relative}")

    joined = "\n".join(text_by_name.values())
    required = (
        "destination_path",
        "migration_prefix_sha256",
        "DiagnosticsCounterV1",
        "DiagnosticsJobFailureV1",
        "DiagnosticSeverityV1",
        "dropped_since_process_start",
        "malformed_line_count",
        "truncated_line_count",
        "O_DIRECTORY",
        "O_NOFOLLOW",
        "O_EXCL",
        "RENAME_EXCL",
        "AT_SYMLINK_NOFOLLOW",
        "reject_extended_acl",
        "export_diagnostics_v1",
        "complete: true",
        'media_type: "application/json"',
    )
    for term in required:
        if term not in joined:
            errors.append(f"required diagnostics boundary missing: {term}")
    for term in FORBIDDEN_SOURCE_TERMS:
        if term in joined:
            errors.append(f"legacy diagnostics contract remains: {term}")

    exporter = text_by_name.get(
        "crates/wardrobe-platform/src/diagnostics_export.rs", ""
    )
    for forbidden in (
        "CredentialPort",
        "reqwest::",
        "OpenAiResponsesHttpTransport",
        "source_content",
    ):
        if forbidden in exporter:
            errors.append(f"exporter reaches forbidden capability: {forbidden}")
    if text_by_name.get("crates/wardrobe-core/src/diagnostics_backend.rs", "").find(
        "serde_json::"
    ) >= 0:
        errors.append("domain diagnostics contract depends on serde_json runtime")

    return SourceValidation(
        tuple(errors),
        _aggregate_hash(contents),
        len(contents),
    )


def _result_summary(result: CommandResult) -> dict[str, Any]:
    return {
        "returncode": result.returncode,
        "output_sha256": result.output_sha256,
        "output_bytes": result.output_bytes,
        "duration_ms": result.duration_ms,
        "timed_out": result.timed_out,
        "output_limit_exceeded": result.output_limit_exceeded,
        "launch_failed": result.launch_failed,
    }


def _command_error(check: CommandCheck, result: CommandResult) -> str | None:
    if result.returncode != 0:
        return f"{check.name} failed"
    if result.timed_out or result.output_limit_exceeded or result.launch_failed:
        return f"{check.name} did not complete within evaluator bounds"
    if check.compiled_smoke:
        output = result.captured_output.decode(errors="replace")
        if (
            "running 1 test" not in output
            or "diagnostics_export_uses_real_sqlite_log_and_atomic_filesystem_path"
            not in output
            or "test result: ok" not in output
        ):
            return "compiled diagnostics smoke did not execute exactly once"
    return None


def _remove_outputs(evidence_dir: Path) -> None:
    for requirement in REQUIREMENT_IDS:
        (evidence_dir / f"{requirement}.json").unlink(missing_ok=True)
    (evidence_dir / DIAGNOSTICS_NAME).unlink(missing_ok=True)


def _public_summary(
    requirement: str,
    packet: PacketValidation,
    source: SourceValidation,
    check_count: int,
) -> dict[str, Any]:
    common: dict[str, Any] = {
        "packet_sha256": packet.sha256,
        "source_sha256": source.sha256,
        "source_file_count": source.file_count,
        "checks_passed": check_count,
        "compiled_smoke": True,
    }
    if requirement in DEFERRED_REQUIREMENT_IDS:
        limitations = {
            "SYS-REL-002": "Packaged clean-machine network-disabled certification deferred.",
            "SYS-SEC-002": "Manual live Keychain inspection deferred.",
            "SYS-A11Y-001": "Aggregate manual keyboard and screen-reader certification deferred.",
        }
        return {
            **common,
            "feature_enabled": False,
            "acceptance_claim": "deferred_not_passed",
            "deferred_limitation": limitations[requirement],
        }
    return {
        **common,
        "feature_enabled": True,
        "acceptance_claim": "focused_local_requirement_passed",
    }


def _write_bounded(path: Path, value: dict[str, Any]) -> None:
    data = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    if len(data) > MAX_ARTIFACT_BYTES:
        raise ValueError("diagnostics evaluator artifact exceeds bound")
    write_atomic_json(path, value)


def evaluate(root: Path, evidence_dir: Path, selected: set[str]) -> int:
    if not (selected & TRIGGER_REQUIREMENT_IDS):
        return 0
    evidence_dir.mkdir(parents=True, exist_ok=True)
    _remove_outputs(evidence_dir)
    recorded_at = utc_now()
    packet = validate_packet(root)
    source = validate_source(root)
    failures = [*packet.errors, *source.errors]
    checks: dict[str, dict[str, Any]] = {}
    smoke_count = 0

    if not failures:
        environment = os.environ.copy()
        environment.pop("HARNESS_RUN_DIR", None)
        environment.pop("HARNESS_EVIDENCE_DIR", None)
        environment.pop("OPENAI_API_KEY", None)
        for check in COMMAND_CHECKS:
            result = run_bounded_command(
                list(check.command),
                cwd=root,
                env=environment,
                timeout_seconds=COMMAND_TIMEOUT_SECONDS,
                capture_output=check.compiled_smoke,
            )
            checks[check.name] = _result_summary(result)
            error = _command_error(check, result)
            if error:
                failures.append(error)
                break
            smoke_count += int(check.compiled_smoke)
    if not failures and smoke_count != 1:
        failures.append("evaluator requires exactly one compiled diagnostics smoke")

    diagnostics = {
        "schema_version": 1,
        "status": "fail" if failures else "pass",
        "recorded_at": recorded_at,
        "failures": list(dict.fromkeys(failures)),
        "packet_sha256": packet.sha256,
        "source_sha256": source.sha256,
        "source_file_count": source.file_count,
        "checks": checks,
        "compiled_smoke_count": smoke_count,
        "external_credentials_used": False,
        "packaged_clean_machine_tested": False,
        "manual_keychain_inspection_tested": False,
        "manual_accessibility_certification_tested": False,
    }
    if failures:
        _write_bounded(evidence_dir / DIAGNOSTICS_NAME, diagnostics)
        return 1

    written: list[Path] = []
    try:
        for requirement in sorted(REQUIREMENT_IDS):
            deferred = requirement in DEFERRED_REQUIREMENT_IDS
            payload = {
                "schema_version": 1,
                "requirement_id": requirement,
                "status": "deferred" if deferred else "pass",
                "test": (
                    "p09_diagnostics::deferred_external_certification"
                    if deferred
                    else "p09_diagnostics::focused_redacted_export_verification"
                ),
                "recorded_at": recorded_at,
                "details": {
                    "public_summary": _public_summary(
                        requirement, packet, source, len(checks)
                    )
                },
            }
            path = evidence_dir / f"{requirement}.json"
            _write_bounded(path, payload)
            written.append(path)
        _write_bounded(evidence_dir / DIAGNOSTICS_NAME, diagnostics)
    except BaseException:
        for path in written:
            path.unlink(missing_ok=True)
        (evidence_dir / DIAGNOSTICS_NAME).unlink(missing_ok=True)
        raise
    return 0


if __name__ == "__main__":
    sys.exit(2)
